config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
      resources :programmers
      resources :customers
      resources :software_engineerings
      resources :offers
      resources :portfolios
      resources :projects

      root to: "programmers#index"
    end
  # devise_for :software_engineerings
  root "home#index"


  get '/offers/new/:id', to: 'offers#new', as: 'new_offer'
  resources :offers, except: :new


  get 'projects/:id/:offer_id/accepted', to: 'projects#offer_accepted', as:'offer_accepted'
  get 'projects/:id/status', to: 'projects#update_status', as:'status_update'
  resources :projects


  resources :portfolios, only: [:index, :edit, :update]


  devise_for :programmers, controllers: { registrations: 'programmers/registrations',
                                          sessions: 'programmers/sessions', unlocks: 'programmers/unlocks',
                                          passwords: 'programmers/passwords', confirmations: 'programmers/confirmations'}


  devise_for :customers, controllers: { registrations: 'customers/registrations',
                                     sessions: 'customers/sessions', unlocks: 'customers/unlocks',
                                     passwords: 'customers/passwords', confirmations: 'customers/confirmations'}

  devise_for :software_engineerings, controllers: { registrations: 'software_engineerings/registrations',
                                          sessions: 'software_engineerings/sessions', unlocks: 'software_engineerings/unlocks',
                                          passwords: 'software_engineerings/passwords', confirmations: 'software_engineerings/confirmations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    belongs_to :programmer
    validates_uniqueness_of :programmer_id, :message => "programmer can only        
                                     have one Portfolio"
    validates :programmer_id, presence: true
end

app/controllers/admin/portfolios_controller.rb
module Admin
  class PortfoliosController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :authenticate_programmer!
  before_action :set_portfolio, only: [:index, :edit, :update]

  # GET /portfolios
  # GET /portfolios.json
  def index
    # @portfolios = Portfolio.all
  end

  # GET /portfolios/1
  # GET /portfolios/1.json
  # def show
  # end

  # GET /portfolios/new
  # def new
  #   @portfolio = Portfolio.new
  # end

  # GET /portfolios/1/edit
  def edit
  end

  # POST /portfolios
  # POST /portfolios.json
  # def create
  #   @portfolio = Portfolio.new(portfolio_params)

  #   respond_to do |format|
  #     if @portfolio.save
  #       format.html { redirect_to @portfolio, notice: 'Portfolio was successfully created.' }
  #       format.json { render :show, status: :created, location: @portfolio }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @portfolio.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /portfolios/1
  # PATCH/PUT /portfolios/1.json
  def update
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully updated.' }
        format.json { render :index, status: :ok, location: @portfolio }
      else
        format.html { render :edit }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolios/1
  # DELETE /portfolios/1.json
  # def destroy
  #   @portfolio.destroy
  #   respond_to do |format|
  #     format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio
      @portfolio = current_programmer.portfolio
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portfolio_params
      params.require(:portfolio).permit(:image, :is_employed, :about, :cv)
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= render  'projects/navbar_users/navbar_users' %>
<br/>


<div class="col-md-12 heading-section"  style="width: 80%; position: relative;
  left: 20%; " >
  <h3 style="text-align: center;"> Edit portfolio</h3>
      <%= form_with(model: portfolio, local: true) do |form| %>
        <% if portfolio.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(portfolio.errors.count, "error") %> prohibited this portfolio from being saved:</h2>

            <ul>
            <% portfolio.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div class="card "  >
         <div class="card-body px-lg-4 pt-0">

              <!-- Form -->
           <form class="text-center"  >
              

              <div class="md-form">
                <%= form.label :about %>
                <%= form.text_area :about, class:"form-control md-textarea" %>
              </div>
              <br/>
               <div class="card-deck">
                <div class="col-sm-6">
                  <%= form.label :image %>
                  <%= form.text_field :image, class:"form-control md-textarea" %>
                </div>

                <div class="col-sm-6">
                  <%= form.label :cv %>
                  <%= form.text_field :cv, class:"form-control"  %>
                </div>
              </div>
              <br/>
              <div class="field">
                <%= form.label :is_employed %>
                <%= form.check_box :is_employed %>
              </div>

              <div class="container-login100-form-btn" style="width:20%; position: relative; left: 80%;">
                <%= form.submit 'update portfolio', class:"login100-form-btn" %>
               </div>
            </form>
            </div>

        </div>
      <% end %>
</div>

app/views/portfolios/edit.html.erb
    <%= render 'form', portfolio: @portfolio %>

    <%= link_to 'Back', portfolios_path%>

app/views/portfolios/index.html.erb
<%= render  'projects/navbar_users/navbar_users' %>
<p id="notice"><%= notice %></p>

   
<div class="col-md-12 heading-section"  style="width: 80%; position: relative;
  left: 20%; " >

    
    
     <div class="card" style="width: 63rem; height: 38rem;">
          <div class="card-body" >
            <h5 class="card-title">
            <%= current_programmer.name%>
           <img style = "width:20%;   border-radius: 30%; position: relative; left: 70%;" src=<%= @portfolio.image %> /> 
            </h5>
              <p class="card-text"> About Me: <%= @portfolio.about %></p>
          </div>
              <hr/>
           <div class="card-body">
          <h5>expirence : </h5>
            <p> bla bla bla bla bla blavbla bla bla bla bla bla </p>
          
            </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"> employed : <%= @portfolio.is_employed %></li>
          <li class="list-group-item" ><%=  link_to 'CV',@portfolio.cv, class:"card-link" %></li>
          
        </ul>
       
      </div>
      <br/>
        <%= link_to 'Edit', edit_portfolio_path(@portfolio) %>
        |
         <%= link_to 'Back', offers_path %>
</div>

app/views/portfolios/new.html.erb
<h1>New Portfolio</h1>

<%= render 'form', portfolio: @portfolio %>

<%= link_to 'Back', portfolios_path %>

app/views/portfolios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @portfolio.image %>
</p>

<p>
  <strong>Is employed:</strong>
  <%= @portfolio.is_employed %>
</p>

<p>
  <strong>About:</strong>
  <%= @portfolio.about %>
</p>

<p>
  <strong>Cv:</strong>
  <%= @portfolio.cv %>
</p>

<%= link_to 'Edit', edit_portfolio_path(@portfolio) %> |