config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
      resources :programmers
      resources :customers
      resources :software_engineerings
      resources :offers
      resources :portfolios
      resources :projects

      root to: "programmers#index"
    end
  # devise_for :software_engineerings
  root "home#index"


  get '/offers/new/:id', to: 'offers#new', as: 'new_offer'
  resources :offers, except: :new


  get 'projects/:id/:offer_id/accepted', to: 'projects#offer_accepted', as:'offer_accepted'
  get 'projects/:id/status', to: 'projects#update_status', as:'status_update'
  resources :projects


  resources :portfolios, only: [:index, :edit, :update]


  devise_for :programmers, controllers: { registrations: 'programmers/registrations',
                                          sessions: 'programmers/sessions', unlocks: 'programmers/unlocks',
                                          passwords: 'programmers/passwords', confirmations: 'programmers/confirmations'}


  devise_for :customers, controllers: { registrations: 'customers/registrations',
                                     sessions: 'customers/sessions', unlocks: 'customers/unlocks',
                                     passwords: 'customers/passwords', confirmations: 'customers/confirmations'}

  devise_for :software_engineerings, controllers: { registrations: 'software_engineerings/registrations',
                                          sessions: 'software_engineerings/sessions', unlocks: 'software_engineerings/unlocks',
                                          passwords: 'software_engineerings/passwords', confirmations: 'software_engineerings/confirmations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :customer
    has_many :offers, :dependent => :destroy
    has_many :programmers, through: :offers
end

app/controllers/admin/projects_controller.rb
module Admin
  class ProjectsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_customer!
  before_action :set_project, only: [:show, :edit, :update, :destroy, :offer_accepted, :update_status]

  # GET /projects
  # GET /projects.json
  def index
    @projects = current_customer.projects
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @is_accepted = @project.offers.any?{ |offer| offer.is_accepted == true}
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.update(customer_id: current_customer.id)
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def offer_accepted
    if @project.offers.where.not(id: params[:offer_id]).destroy_all
      if @project.offers.where(id: params[:offer_id]).update(is_accepted: true)
        if  @project.update(status: "underway")
          redirect_to project_path(params[:id])
        end
      end
    end
  end

  def update_status
    if @project.status == "underway"
      @project.status = "completed"
    else
      @project.status = "underway"
    end
    @project.save()
    redirect_to project_path(params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = current_customer.projects.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :status, :description, :requirements, :budget)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
 <%= render  'projects/navbar_users/navbar_users' %>
<br/>
<br/>
<br/>
<br/>

 <div class="col-md-12 heading-section"  style="width: 80%; position: relative;
  left: 20%; " >	


        <%= form_with(model: project, local: true) do |form| %>
          <% if project.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

              <ul>
              <% project.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

               <!-- Material form contact -->
          <div class="card " >
         <% if  current_page?(new_project_path) %>
          <h5 class="card-header info-color white-text text-center py-4">
              <strong>New Project</strong>
          </h5>
          <%elsif current_page?(edit_project_path) %>
          <h5 class="card-header info-color white-text text-center py-4">
              <strong>Edit Project</strong>
          </h5>
         <%end%>
           <br/>
        

    <!--Card content-->
    <div class="card-body px-lg-5 pt-0">

              <!-- Form -->
              <form class="text-center"  >


                    <div class="card-deck">

                    

                      <div class=" col-sm-8">
                        <%= form.label :name%>
                        
                        <%= form.text_field :name, id:"materialContactFormName", class:"form-control" %>
                      </div>

                      <div class=" col-sm-4">
                        <%= form.label :budget %>
                        <%= form.text_field :budget , class:"form-control"%>
                      </div>

                    </div>
                    <br/>

                    <div class="md-form">
                      <%= form.label :requirements %>
                      <%= form.text_area :requirements, class:"form-control md-textarea" %>
                    </div>
                    <br/>

                    <div class="md-form">
                      <%= form.label :description %>
                      <%= form.text_area :description, class:"form-control md-textarea" %>
                    </div>
                    <br/>
                  

                  

                    <div class="container-login100-form-btn" style="width:20%; position: relative; left: 80%;" >

                      <% if  current_page?(new_project_path) %>
                      
                        <%= form.submit "create project", class:"login100-form-btn" %> 
                      <% elsif%>
                         <%= form.submit "update project", class:"login100-form-btn" %> 
                      <%else%>
                        <%= form.submit  %> 
                      <%end%>
                       
                      
                   
                    </div>

                    <%= link_to 'Back', projects_path  %>
                </form>
              <!-- Form -->

    </div>

  </div>
<!-- Material form contact -->
        <% end %>
      
</div>

app/views/projects/edit.html.erb
<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
 <%= render  'projects/navbar_users/navbar_users' %>

 <div class="col-md-12 heading-section"  style="width: 80%; position: relative; left: 20%;" >	
      <p id="notice"><%= notice %></p> 
		            <h2 class=" ">Projects</h2>
                
                <div class="text-right ">
                    <%= link_to 'New Project', new_project_path , class:" btn btn-primary " %> 
                </div>
		           <hr/>

                <% @projects.each do |project| %>

                  <div class="card  " style="width: 100%;">
                    <div class="card-header ">
                      Name : <%= project.name %>
                    </div>

                    <div class="card-body">
                      <h6 class="card-title">status : <%= project.status %> </h6>
                      <h6 class="card-title">requirements :  <%= project.requirements %> </h6>
                      <h6 class="card-title">budget :  <%= project.budget %> </h6>
                      <h6 class="card-text">description : <%= project.description %> </h6> 
                      <h6 colspan="3" ></h6>




                        <!-- NO NEED ANY MORE -->
                           <!-- <td><% project.name %></td>
                            <td ><% project.status %></td>
                            <td><% project.description %></td>
                            <td><% project.requirements %></td>
                            <td><% project.budget %></td>
                            <td><% link_to 'Show', project %></td>
                            <td><% link_to 'Edit', edit_project_path(project) %></td>
                            <td><% link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
                        <!-- END -->

                      
                    </div>

                    <div class="card-footer text-right">
                        
                       <%= link_to 'Show', project, class:"btn btn-primary" %>
                        <%= link_to 'Edit', edit_project_path(project),class:"btn btn-primary"  %>
                        <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } ,class:"btn btn-danger" %>
                        
                    </div>
                    
                   </div>
                   <br/>
                 <% end %>

</div>














   

app/views/projects/new.html.erb
<%= render 'form', project: @project %>

app/views/projects/show.html.erb
<%= render  'projects/navbar_users/navbar_users' %>
<br/>

   


<div class="col-md-12 heading-section"  style="width: 80%; position: relative;
  left: 20%; " >	
     <p id="notice"><%= notice %></p>
       

              <div class="card  " style="width: 100%;">
                    <div class="card-header ">
                      Name : <%= @project.name %>
                    </div>

                    <div class="card-body">
                      <h6 class="card-title">status : <%= @project.status %> </h6>
                      <h6 class="card-title">requirements :  <%= @project.requirements %> </h6>
                      <h6 class="card-title">budget :  <%= @project.budget %> </h6>
                      <h6 class="card-text">description : <%= @project.description %> </h6> 
                      
 
                    </div>

                    <div class="card-footer text-right">
                       
                        <div style="width:20%; position: relative; left: 80%;">
                          <% if @project.status == "underway"%>
                              <strong></strong>
                              <% @project.status.upcase %> 
                              <%= link_to 'COMPLETED', status_update_path(@project), data: { confirm: "You want to change the status of project to COMPLETED\nAre you sure?"},class:"login100-form-btn" %>
                              
                            <%elsif @project.status == "completed"%>
                              <strong></strong>
                              <% @project.status.upcase %> 
                              <%= link_to 'UNDERWAY', status_update_path(@project), data: { confirm: "You want to change the status of project to UNDERWAY\nAre you sure?"},class:"login100-form-btn" %> 
                              
                          <% end %>
                             
                          </div>
                        
                        <div class="text-left">
                            <%= link_to 'Edit', edit_project_path(@project) %> |
                            <%= link_to 'Back', projects_path %>
                        </div>

                     </div>
                      
               </div>
               <br/>
              
      
            <h3>Offers : </h3>
             <hr/>

           <div class="card-columns">
            <% @project.offers.each do |offer| %>
                  <div class="card  " >
                      <div class=" card-body">
                        <h5 class="card-title">prgrammer name: <%= offer.programmer.username%> </h4>
                        <h6 class="card-title" >Time: <%= offer.time %> </h6>
                        <h6 class="card-title" >Budget:  <%= offer.budget %> </h6>
                        <h6 class="card-text" >Description: <%= offer.description %> </h6>
                           <div style="max-width: 30%;  position: relative; left: 70%;">  
                              <% if @is_accepted == false %>
                                <%= link_to 'Accepted', offer_accepted_path(@project,offer), data: { confirm: "Are you sure?\nNote: All the other offers for this project will be deleted and your project will not appear to programmers" }, class:"login100-form-btn" %>
                              <%end%>
                          </div>
                      </div>
                      
                   </div>
                  
            <% end %>
             </div>
</div>