config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
      resources :programmers
      resources :customers
      resources :software_engineerings
      resources :offers
      resources :portfolios
      resources :projects

      root to: "programmers#index"
    end
  # devise_for :software_engineerings
  root "home#index"


  get '/offers/new/:id', to: 'offers#new', as: 'new_offer'
  resources :offers, except: :new


  get 'projects/:id/:offer_id/accepted', to: 'projects#offer_accepted', as:'offer_accepted'
  get 'projects/:id/status', to: 'projects#update_status', as:'status_update'
  resources :projects


  resources :portfolios, only: [:index, :edit, :update]


  devise_for :programmers, controllers: { registrations: 'programmers/registrations',
                                          sessions: 'programmers/sessions', unlocks: 'programmers/unlocks',
                                          passwords: 'programmers/passwords', confirmations: 'programmers/confirmations'}


  devise_for :customers, controllers: { registrations: 'customers/registrations',
                                     sessions: 'customers/sessions', unlocks: 'customers/unlocks',
                                     passwords: 'customers/passwords', confirmations: 'customers/confirmations'}

  devise_for :software_engineerings, controllers: { registrations: 'software_engineerings/registrations',
                                          sessions: 'software_engineerings/sessions', unlocks: 'software_engineerings/unlocks',
                                          passwords: 'software_engineerings/passwords', confirmations: 'software_engineerings/confirmations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/offer.rb
class Offer < ApplicationRecord
    belongs_to :programmer
    validates :programmer_id, presence: true

    belongs_to :project
    validates :project_id, presence: true
end

app/controllers/admin/offers_controller.rb
module Admin
  class OffersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :authenticate_programmer!
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  # GET /offers
  # GET /offers.json
  def index
    @offers = current_programmer.offers
    @projects = Project.all
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
    @project = Project.find(params[:id])
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(offer_params)
    respond_to do |format|
      if @offer.update(programmer_id: current_programmer.id)
        format.html { redirect_to @offer, notice: 'Offer was successfully created.' }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url, notice: 'Offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = current_programmer.offers.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      params.require(:offer).permit(:description, :time, :budget, :project_id)
    end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.erb
 <%= render  'projects/navbar_users/navbar_users' %>

 <div class="col-md-12 heading-section"  style="width: 80%; position: relative; left: 20%;" >	
      <p id="notice"><%= notice %></p> 

    <%= form_with(model: offer, local: true) do |form| %>
      <% if offer.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

          <ul>
          <% offer.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <%= form.hidden_field :project_id, value: params[:id] %>
         <div class="card "  >

             <% if  current_page?(new_offer_path) %>
              <h5 class="card-header info-color white-text text-center py-4">
                  <strong>New offer</strong>
              </h5>
              <%elsif current_page?(edit_offer_path) %>
              <h5 class="card-header info-color white-text text-center py-4">
                  <strong>Edit offer</strong>
              </h5>
            <%end%>
              <br/>
         <!--Card content-->
          <div class="card-body px-lg-4 pt-0">

              <!-- Form -->
              <form class="text-center"  >


                        <div class="card-deck">

                            <div class="col-sm-6">
                              <%= form.label :time %>
                              <%= form.text_field :time, class:"form-control"  %>
                            </div>

                            <div class="col-sm-6">
                              <%= form.label :budget %>
                              <%= form.text_field :budget, class:"form-control" %>
                            </div>
                        </div>

                        <div class="md-form">
                          <%= form.label :description %>
                          <%= form.text_area :description, class:"form-control md-textarea" %>
                        </div>
                        <br/>

                        <div class="container-login100-form-btn" style="width:20%; position: relative; left: 80%;" >

                              <% if  current_page?(new_offer_path) %>
                              
                                <%= form.submit "create offer", class:"login100-form-btn" %> 
                              <% elsif%>
                                <%= form.submit "update offer", class:"login100-form-btn" %> 
                              <%else%>
                                <%= form.submit  %> 
                              <%end%>  
                          
                        </div>
                            <%= link_to 'Back', offers_path %>
               </form>

          
        </div>
      </div>
    <% end %>
    
</div>

app/views/offers/edit.html.erb
<%= render 'form', offer: @offer %>

<%= link_to 'Show', @offer %> |

app/views/offers/index.html.erb
<%= render  'projects/navbar_users/navbar_users' %>


<div class="col-md-12 heading-section"  style="width: 80%; position: relative;
  left: 20%; " >	
     
        <p class="alert"><%= notice %></p>
      
          <nav class="navbar navbar-expand-lg navbar-light bg-light">
             <div class="collapse navbar-collapse" id="navbarNav">
                 <ul class="navbar-nav">
                    <li class="nav-item ">
                     <button class="nav-link" onclick="toggleOne()">Offers </button> 
                    </li>
                    <li class="nav-item ">
                       <button class="nav-link" onclick="toggleTwo()">Projects</button>
                    </li>
                   </ul>
              </div>
           </nav>
            <br/>
          

          
          
          <div id="offers">
              <h3>Offers : </h3>

                  <% @offers.each do |offer| %>
                    <div class="card  " >
                      <div class=" card-body">
                       
                          <h5 class="card-text"> description: <%= offer.description %></h5>
                          <h5 class="card-title"> time:   <%= offer.time %></h5>
                          <h5 class="card-title"> budget:   <%= offer.budget %></h5>
                          

                          
                        </tr>
                          <div class="card-footer text-right">
                            <%= link_to 'Show', offer ,  class:"btn btn-primary"%>
                            <%= link_to 'Edit', edit_offer_path(offer),  class:"btn btn-primary" %>
                            <%= link_to 'Destroy', offer, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-danger"  %>
                       </div> 
                      </div>

                     
                    </div>
                    <br/>
                  <% end %>

                
             
          </div>



           <div id="projects" style="display:none;">
           <p id="notice"><%= notice %></p>

           <h3>Projects : </h3>

          

            
              <% @projects.each do |project| %>
                <div class="card " >

                     <div class="card-header ">
                       <h5>  client name: <%= project.customer.username %>  </h5>
                      </div>

                      <div class=" card-body">
                        <h6 class="card-title"> project name : <%= project.name %> </h6>
                        <h6 class="card-title"> status: <%= project.status %> </h6>
                        <h6 class="card-text"> description: <%= project.description %></h6>
                        <h6 class="card-title">requirements: <%= project.requirements %> </h6>
                        <h6 class="card-title"> budget: <%= project.budget %></h6>
                      
                        <div style="max-width: 20%;  position: relative; left: 80%;">  
                          <%= link_to 'Create Offer', new_offer_path(project) , class:"login100-form-btn" %>
                        </div>
                      </div>
                    
                </div>
                <br/>
              <% end %>
              
          </div>
         
         
          <script>
          function toggleOne(){
            document.getElementById("projects").style.display = "none"
            document.getElementById("offers").style.display = ""
            
          }
          function toggleTwo(){
            document.getElementById("offers").style.display = "none"
            document.getElementById("projects").style.display = ""
          }
          </script>

</div>

app/views/offers/new.html.erb
 <%= render  'projects/navbar_users/navbar_users' %>

<br/>

 <div class="col-md-12 heading-section"  style="width: 80%; position: relative;
  left: 20%; " >	
    <h3>Project</h3>
    <div class="card " >

                     <div class="card-header ">
                       <h5>  client name: <%= @project.customer.username %>  </h5>
                      </div>

                      <div class=" card-body">
                        <h6 class="card-title"> project name : <%= @project.name %> </h6>
                        <h6 class="card-title"> status: <%= @project.status %> </h6>
                        <h6 class="card-text"> description: <%= @project.description %></h6>
                        <h6 class="card-title">requirements: <%= @project.requirements %> </h6>
                        <h6 class="card-title"> budget: <%= @project.budget %></h6>
                      </div>
    </div>
    <hr/>
    
    <%= render 'form', offer: @offer %>

    

</div>

app/views/offers/show.html.erb
 <%= render  'projects/navbar_users/navbar_users' %>

 <div class="col-md-12 heading-section"  style="width: 80%; position: relative; left: 20%;" >	
      <p id="notice"><%= notice %></p> 


        <h3>Project </h3>
            <div class="card " >

              <div class="card-header ">
                <h5>  client name : <%= @offer.project.customer.username %>  </h5>
              </div>

              <div class=" card-body">

                <h6 class="card-title">Name : <%= @offer.project.name %> </h6>
                <h6 class="card-title"> Status :<%= @offer.project.status %></h6>
                <h6 class="card-text"> Description :<%= @offer.project.description %></h6>
                <h6 class="card-title"> Requirements : <%=  @offer.project.requirements %></h6>
                <h6 class="card-title"> Budget: <%=  @offer.project.budget %></h6>
                
              </div>
            </div>

        <hr/>


        <h3>Offer </h3>

           <div class="card " >
               <div class=" card-body">

               <h6 class="card-text">Description : <%= @offer.description %><h6>
               <h6 class="card-title">Time :  <%= @offer.time %><h6>
               <h6 class="card-title">Budget: <%= @offer.budget %><h6>
       
            </div>
 
          </div>
          <br/>
          <%= link_to 'Edit', edit_offer_path(@offer) %>  |
          <%= link_to 'Back', offers_path %>
</div>